application: rieya-uc
version: 1
runtime: python27
api_version: 1
threadsafe: yes
  
handlers:
- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon\.ico

- url: /static
  static_dir: static
- url: /p/static
  static_dir: static
  
- url: /
  script: handlers.app
- url: /newpost
  script: handlers.app
  login: admin
- url: /p/([0-9a-z-//]+)
  script: handlers.app
- url: /.*
  script: handlers.app



libraries:
- name: webapp2
  version: "2.5.1"
- name: jinja2                                                                  
  version: latest           


                                                    
